"""Create baseline migration

Revision ID: 41b99c93cd79
Revises: e2661fbde2f0
Create Date: 2024-06-14 04:30:19.601483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41b99c93cd79'
down_revision: Union[str, None] = 'e2661fbde2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('author', sa.String(), nullable=True))
    op.add_column('statistics', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('statistics', sa.Column('like', sa.BOOLEAN(), nullable=True))
    op.add_column('statistics', sa.Column('view', sa.BOOLEAN(), nullable=True))
    op.drop_column('statistics', 'user_view_ids')
    op.drop_column('statistics', 'user_like_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('user_like_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('statistics', sa.Column('user_view_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('statistics', 'view')
    op.drop_column('statistics', 'like')
    op.drop_column('statistics', 'user_id')
    op.drop_column('statistics', 'author')
    # ### end Alembic commands ###
