version: "3"

services:
  grpc_service:
    build:
      context: ../../mysite/grpc_api/
      dockerfile: Dockerfile.grpc
    ports:
      - "50051:50051"
    networks:
      - meowview-network
    depends_on:
      - postgresql
    environment:
      - DATABASE_NAME=posts_database
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=postgresql
      - DATABASE_PORT=5432
      - DOCKER_CLI_CONFIG=/etc/docker/daemon.json
    
  web:
    build:
      context: ../../mysite/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - postgresql
      - grpc_service
      - kafka_db_connector
    networks:
      - meowview-network
    environment:
      - DATABASE_NAME=users_database
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=postgresql
      - DATABASE_PORT=5432
      - GRPC_HOST=grpc_service
      - GRPC_PORT=50051
      - DOCKER_CLI_CONFIG=/etc/docker/daemon.json

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - meowview-network
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"

    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092, OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092, OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
    networks:
      - meowview-network

  kafka_db_connector:
    build:
      context: ../../mysite/kafka_service/
      dockerfile: Dockerfile
    networks:
      - meowview-network
    depends_on:
      - postgresql
    environment:
      - DATABASE_NAME=statistic_database
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=postgresql
      - DATABASE_PORT=5432
      - DOCKER_CLI_CONFIG=/etc/docker/daemon.json

  postgresql:
    container_name: "meowview-postgresql"
    image: postgres:15.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: users_database, posts_database, statistic_database
    ports:
      - "5432:5432"
    networks:
      - meowview-network
    volumes:
      - ./configs/create-multiple-db-with-users.sh:/docker-entrypoint-initdb.d/create-multiple-db-with-users.sh:ro
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: "meowview-pgadmin"
    image: dpage/pgadmin4
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin/;
      chmod 600 /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    networks:
      - meowview-network
    volumes:
      - ./configs/servers.json:/pgadmin4/servers.json:ro
      - ./configs/pgpass:/pgadmin4/pgpass:ro

networks:
  meowview-network:
    name: "meowview-network"
    driver: bridge

