openapi: 3.0.0
info:
  title: User API
  description: API для управления пользователями (регистрация, аутентификация, обновление)
  version: 1.0.0

paths:
  /register:
    post:
      summary: Регистрация пользователя
      description: Создание новой учетной записи пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: johndoe
                password:
                  type: string
                  format: password
                  example: secretpassword
                email:
                  type: string
                  format: email
                  example: johndoe@example.com
              required:
                - username
                - password
                - email
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
        '400':
          description: Ошибка ввода данных

  /login:
    post:
      summary: Аутентификация пользователя
      description: Вход пользователя в систему
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: joh
