FROM ubuntu

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update
RUN apt-get install -y python3 python3-pip libpq-dev
RUN apt-get clean

RUN pip3 install --upgrade pip

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

# Expose the port the gRPC service will run on
EXPOSE 50051

ENTRYPOINT ["/app/entrypoint.sh"]

# Command to run the gRPC service
CMD ["python3", "server.py"]