# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: posts.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bposts.proto\x12\x05posts\"E\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05login\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05image\x18\x04 \x01(\x0c\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05login\x18\x02 \x01(\t\"G\n\x08GetReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x19\n\x04post\x18\x03 \x01(\x0b\x32\x0b.posts.Post\"\'\n\nAddRequest\x12\x19\n\x04post\x18\x01 \x01(\x0b\x32\x0b.posts.Post\",\n\x08\x41\x64\x64Reply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05login\x18\x02 \x01(\t\"/\n\x0b\x44\x65leteReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\rUpdateRequest\x12\x19\n\x04post\x18\x02 \x01(\x0b\x32\x0b.posts.Post\"/\n\x0bUpdateReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\x0bListRequest\x12\r\n\x05login\x18\x01 \x01(\t\"H\n\tListReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x19\n\x04list\x18\x03 \x03(\x0b\x32\x0b.posts.Post2\xc9\x02\n\x07Greeter\x12\x34\n\x08SayHello\x12\x13.posts.HelloRequest\x1a\x11.posts.HelloReply\"\x00\x12/\n\x07GetPost\x12\x11.posts.GetRequest\x1a\x0f.posts.GetReply\"\x00\x12/\n\x07\x41\x64\x64Post\x12\x11.posts.AddRequest\x1a\x0f.posts.AddReply\"\x00\x12\x38\n\nDeletePost\x12\x14.posts.DeleteRequest\x1a\x12.posts.DeleteReply\"\x00\x12\x38\n\nUpdatePost\x12\x14.posts.UpdateRequest\x1a\x12.posts.UpdateReply\"\x00\x12\x32\n\x08ListPost\x12\x12.posts.ListRequest\x1a\x10.posts.ListReply\"\x00\x42\x14\x42\nPostsProtoP\x01\xa2\x02\x03PTSb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'posts_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\nPostsProtoP\001\242\002\003PTS'
  _globals['_POST']._serialized_start=22
  _globals['_POST']._serialized_end=91
  _globals['_HELLOREQUEST']._serialized_start=93
  _globals['_HELLOREQUEST']._serialized_end=121
  _globals['_HELLOREPLY']._serialized_start=123
  _globals['_HELLOREPLY']._serialized_end=152
  _globals['_GETREQUEST']._serialized_start=154
  _globals['_GETREQUEST']._serialized_end=193
  _globals['_GETREPLY']._serialized_start=195
  _globals['_GETREPLY']._serialized_end=266
  _globals['_ADDREQUEST']._serialized_start=268
  _globals['_ADDREQUEST']._serialized_end=307
  _globals['_ADDREPLY']._serialized_start=309
  _globals['_ADDREPLY']._serialized_end=353
  _globals['_DELETEREQUEST']._serialized_start=355
  _globals['_DELETEREQUEST']._serialized_end=397
  _globals['_DELETEREPLY']._serialized_start=399
  _globals['_DELETEREPLY']._serialized_end=446
  _globals['_UPDATEREQUEST']._serialized_start=448
  _globals['_UPDATEREQUEST']._serialized_end=490
  _globals['_UPDATEREPLY']._serialized_start=492
  _globals['_UPDATEREPLY']._serialized_end=539
  _globals['_LISTREQUEST']._serialized_start=541
  _globals['_LISTREQUEST']._serialized_end=569
  _globals['_LISTREPLY']._serialized_start=571
  _globals['_LISTREPLY']._serialized_end=643
  _globals['_GREETER']._serialized_start=646
  _globals['_GREETER']._serialized_end=975
# @@protoc_insertion_point(module_scope)
