# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistics.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10statistics.proto\x12\nstatistics\"i\n\x04Post\x12\x0f\n\x07post_id\x18\x01 \x01(\x03\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05image\x18\x04 \x01(\x0c\x12\r\n\x05likes\x18\x05 \x01(\x03\x12\r\n\x05views\x18\x06 \x01(\x03\"%\n\x04User\x12\r\n\x05likes\x18\x01 \x01(\x03\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\"#\n\x10StatisticRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x03\"1\n\x11StatisticResponse\x12\r\n\x05likes\x18\x01 \x01(\x03\x12\r\n\x05views\x18\x02 \x01(\x03\"!\n\x0fTopPostsRequest\x12\x0e\n\x06\x66ilter\x18\x01 \x01(\t\"3\n\x10TopPostsResponse\x12\x1f\n\x05posts\x18\x01 \x03(\x0b\x32\x10.statistics.Post\"\x11\n\x0fTopUsersRequest\"3\n\x10TopUsersResponse\x12\x1f\n\x05users\x18\x01 \x03(\x0b\x32\x10.statistics.User2\xeb\x01\n\x07Greeter\x12N\n\rGetStatistics\x12\x1c.statistics.StatisticRequest\x1a\x1d.statistics.StatisticResponse\"\x00\x12G\n\x08TopPosts\x12\x1b.statistics.TopPostsRequest\x1a\x1c.statistics.TopPostsResponse\"\x00\x12G\n\x08TopUsers\x12\x1b.statistics.TopUsersRequest\x1a\x1c.statistics.TopUsersResponse\"\x00\x42\x19\x42\x0fStatisticsProtoP\x01\xa2\x02\x03STSb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\017StatisticsProtoP\001\242\002\003STS'
  _globals['_POST']._serialized_start=32
  _globals['_POST']._serialized_end=137
  _globals['_USER']._serialized_start=139
  _globals['_USER']._serialized_end=176
  _globals['_STATISTICREQUEST']._serialized_start=178
  _globals['_STATISTICREQUEST']._serialized_end=213
  _globals['_STATISTICRESPONSE']._serialized_start=215
  _globals['_STATISTICRESPONSE']._serialized_end=264
  _globals['_TOPPOSTSREQUEST']._serialized_start=266
  _globals['_TOPPOSTSREQUEST']._serialized_end=299
  _globals['_TOPPOSTSRESPONSE']._serialized_start=301
  _globals['_TOPPOSTSRESPONSE']._serialized_end=352
  _globals['_TOPUSERSREQUEST']._serialized_start=354
  _globals['_TOPUSERSREQUEST']._serialized_end=371
  _globals['_TOPUSERSRESPONSE']._serialized_start=373
  _globals['_TOPUSERSRESPONSE']._serialized_end=424
  _globals['_GREETER']._serialized_start=427
  _globals['_GREETER']._serialized_end=662
# @@protoc_insertion_point(module_scope)
